### ISSUE TITLE
Switch Component

### ISSUE THREAD

**Issue by drewbarontini** [mvcss/library#5]
For example:

![library 2015-03-04 17-57-15](https://cloud.githubusercontent.com/assets/30208/6495420/e577a4e0-c297-11e4-8496-578aee9f1f42.jpg)

Similar to a `btn`, but has some different styles and could use the `+action` mixin in #4.

- Full width
- Various sizes
- Fixed-width buttons

**Comment by nickawalsh** [comment]
These are occasionally best achieved with `.has-btn`; I think Bootstrap used to refer to them as Button Groups, but they've since been removed.

**Comment by drewbarontini** [comment]
So you see something like the following (simplified markup)?

```haml
.has-btn
  %a.btn{ href: '#' } Issues
  %a.btn{ href: '#' } Pull Requests
  %a.btn{ href: '#' } Labels
  %a.btn{ href: '#' } Milestones
```

```sass
.has-btn
  / ...

  .btn
    / ...
```

The issue is that you generally have to override a lot of the `.btn` styling, and you'll have to deal with context modifiers (e.g. `.has-btn--fixed`, `.has-btn--fixed--2`) if you want to do various switch (button group) styles. With the referenced example, I think `.has-btn` suffices, but this would be for more built out variations.

**Comment by nickawalsh** [comment]
Right-o. No issues with a switch structure, it'll just be implementation-dependent.

**Comment by drewbarontini** [comment]
I misnamed this one as a structure instead of a component. The idea was to component it by using the shared `+action` mixin from #4, but it might get into too much duplication. Closing for now.
