### ISSUE TITLE
Link Structure

### ISSUE THREAD

**Issue by drewbarontini** [mvcss/library#6]
- `.link` - alias for the `a` tag, which can extend the `%a` placeholder selector
- `.link--bordered`, `.link-inverted`, `.link--muted`, etc.

**Comment by baldwindavid** [comment]
I guess I would have thought this would be a component. Is this a more specific item than say, the button component?

**Comment by drewbarontini** [comment]
In short, yes. The changes from project to project are going to be enough to make it a structure. The differentiation is easy to argue though, so we're removing that delineation in 'v4. 

Out of curiosity, do you find the component vs. structure idea confusing?

**Comment by baldwindavid** [comment]
Sorry for the late reply. The concept of breaking them up makes sense when I read it, but then you have cases like "link" where it might not be totally obvious to me which it should be. I'm not actually using MVCSS (or even Sass) as much as learning from it, so its hard for me to practically assess.

The way I'm structuring applications is pulling in a base library of components and utilities via NPM that are general enough across multiple applications. Variables that exist in the base library are overridable within a specific application.

Then within a specific application, I have the same organization of components/utilities, but specific to only that application. If a component/utility is to be general enough in nature, it may get promoted into the shared overall library. 

So really there is only one decision to make; does the component belong in the shared library or the specific application? By virtue of choosing one of those, most of the questions of portability, dependencies, and size of scope have been answered.

**Comment by drewbarontini** [comment]
No worries at all! Nothing pressing at all with my question :smile: 

That's definitely how we think of Components vs. Structures, but definitely see the need to simplify under a single "Modules" namespace. From there, we can move modules that can be in a shared library into here, which is nice.

Thanks for the feedback! We appreciate any feedback we can get.
